package vista.reclutador;

import vista.reclutador.ListaDeReclutadores;
import modelo.*;
import controlador.ReclutadorData;
import java.util.ArrayList;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Cosquin
 */
public class EditarReclutador extends javax.swing.JInternalFrame {

    private Reclutador reclutador;
    /**
     * Creates new form AgregarReclutador
     */
    public EditarReclutador(Reclutador reclutador) {
        initComponents();
        input_correo.setText(reclutador.getCorreo());
        input_nombre.setText(reclutador.getNombre());
        this.reclutador = reclutador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input_nombre = new javax.swing.JTextField();
        input_correo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnE = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);

        input_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Correo:");

        btnE.setText("Editar");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        jLabel3.setText("Agregar reclutador");

        jButton1.setText("Ver lista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("¿Desea Editarlo?");

        jLabel5.setText("Todos los reclutadores de la Base de Datos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addComponent(btnE))
                    .addComponent(input_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(input_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nombreActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed


        if (verificarSoloLetrasER(  input_nombre.getText()+"")) {
            if (verificarCorreo(input_correo.getText()+"")) {
                reclutador = new Reclutador (reclutador.getId(),input_nombre.getText(),input_correo.getText());                
                ReclutadorData.modificarReclutador(reclutador);
               
                input_correo.setText("");
                input_nombre.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error correo tiene caracteres invalidos");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Error nombre tiene caracteres invalidos");
        }
    }//GEN-LAST:event_btnEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDesktopPane desktop = getDesktopPane();
        desktop.removeAll();
        desktop.repaint();

        ListaDeReclutadores pagina1 = new ListaDeReclutadores();
        pagina1.setVisible(true);
        desktop.add(pagina1);
        desktop.moveToFront(pagina1);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnE;
    private javax.swing.JTextField input_correo;
    private javax.swing.JTextField input_nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

///* -------------------------------------- OTROS VERIFICADORES------------------------------------------------------------------------------
//    public boolean verificadorSoloNumerosER(String texto) {
//        /*Expresión regular*/
//        if (texto.matches("\\d+")) {
//            int numeroEntero = Integer.parseInt(texto);
//            return true;
//
//        } else {
//            return false;
//        }
//    }
//
//    public boolean verificarSoloLetrasER(String texto) {
//        /*Expresion regular*/
//        if (texto.matches("[a-zA-Z]+")) {
//            return true;
//        } else {
//            return false;
//        }
//    }
//
//    public boolean verificarSoloLetrasYEspaciosER(String texto) {
//        /*Expresion regular*/
//        if (texto.matches("[a-zA-Z ]+")) {
//            return true;
//        } else {
//            return false;
//        }
//    }
//
//    public boolean verificadorNumerosEnterosYDecimalesER(String texto) {
//        /* Expresión regular que permite números enteros o decimales */
//        if (texto.matches("\\d+|\\d*\\.\\d+")) {
//            return true;
//        } else {
//            return false;
//        }
//    }
//
//    public boolean verificarLetrasNumeroYEspacios(String texto) {
//        if (texto.matches("[a-zA-Z0-9 ]+")) {
//            return true;
//        } else {
//            return false;
//        }
//    }
//
//   -------------------------------------------------------------------------------------------------------------------------------- */
//}
    public boolean verificarSoloLetrasER(String texto) {
        /*Expresion regular*/
        if (texto.matches("[a-zA-Z]+")) {
            return true;
        } else {
            return false;
        }
    }

    public boolean verificarCorreo(String nombreCorreo) {
        if (nombreCorreo.length() < 6 || nombreCorreo.length() > 30) {
            return false;
        }
        if (!nombreCorreo.contains("@") || !nombreCorreo.contains(".")) {
            return false;
        }
        if (nombreCorreo.indexOf('@') > nombreCorreo.indexOf('.') || nombreCorreo.lastIndexOf('.') > nombreCorreo.length() - 3) {
            return false;
        }
        if (!Character.isLetter(nombreCorreo.charAt(0)) || !Character.isLetter(nombreCorreo.charAt(nombreCorreo.length() - 1))) {
            return false;
        }
        if (nombreCorreo.toLowerCase().contains("ñ") || nombreCorreo.matches(".*[^a-zA-Z0-9.@].*")) {
            return false;
        }
        return true;
    }

}
